### ISSUE TITLE
render problem

### ISSUE THREAD

**Issue by barron9** [kenmaca/react-native-tear-lines#1]
![simulator screen shot - iphone x - 2018-04-02 at 17 16 23](https://user-images.githubusercontent.com/27488285/38199480-9d265e7e-3699-11e8-9a1b-4430adfb329b.png)
hi is this normal?

```
 <View style={{ backgroundColor: "#d7d7d8",flex:1 }}>
	    <Text style={{paddingTop:200, fontSize:24,fontWeight:'800'}}>Son adım.</Text>

	    <Text style={{paddingTop:10, fontSize:24,fontWeight:'200'}}>Siparişinizi Onaylayın.</Text>
  <TearLines
    ref="top"
	    
    color="#FFFFFF"
    backgroundColor="#ffffff"/>
	    <View
    style={{ backgroundColor: "#FFFFFF" ,height:Dimensions.get('window').height}}
	     onLayout={e => {
      this.refs.top.onLayout(e);
    // this.refs.bottom.onLayout(e);
    }} 
     />
	    <Text style={{fontFamily:'Courier New',color:'black'}} >xxx kullancı adress vs vsv vs</Text>
</View>
<View style={{position:'absolute',height:100,backgroundColor:'black',bottom:0,width:Dimensions.get('window').width,flexDirection:'column',padding:20}}><Text style={{fontWeight:'100',color:'white'}}>sipariş onayında kartınızdan xxx TL çekilecektir</Text>

```

**Comment by kenmaca** [comment]
Hey! You need to set the `backgroundColor` prop on `TearLines` to match your actual background, which looks like `#D7D7D8`. You currently have it set to the same colour as your "receipt" background.

**Comment by barron9** [comment]
ok thanks now corrected , and how can i place text inside or after that -> `<tearlines><view>`

**Comment by kenmaca** [comment]
`TearLines` takes children, so you can just pass in whatever component you want, similarly to how a `<View>` works with children.

**Comment by kenmaca** [comment]
In the `<View>` right after `<TearLines>`, you can put whatever component you want (ie, `<Text>`, etc) inside it as "receipt" content.

**Comment by barron9** [comment]
ok thanks, nice add-on & good luck
